export enum TrackingStatus {
    CREATED = "CREATED",
    INFO_RECEIVED = "INFO_RECEIVED",
    IN_TRANSIT = "IN_TRANSIT",
    OUT_FOR_DELIVERY = "OUT_FOR_DELIVERY",
    DELERIVED = "DELERIVED",
    EXCEPTION = "EXCEPTION",
    RETURNED = "RETURNED",
    UNKNOWN = "UNKNOWN",
}